version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      
  test_1:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server
          
  test_2:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
workflows:
    build-and-test:
      jobs:
        - build:
          filters:
            branches:
              only:
                - master
        - test_1:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
        - test_2:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
            requires:
              - build
